# Generated by Django 4.2.5 on 2023-12-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='BillRecord',
        ),
    ]
