# Generated by Django 4.2.5 on 2023-12-25 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_staff_date_of_birth_alter_staff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 25, 8, 25, 37, 659734, tzinfo=datetime.timezone.utc), upload_to='Staff/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
