# Generated by Django 4.2.5 on 2023-12-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_rename_record_billrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillRecord',
        ),
    ]
