# Generated by Django 4.2.5 on 2023-12-26 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 26, 7, 54, 50, 439861, tzinfo=datetime.timezone.utc), upload_to='Stock/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
