# Generated by Django 4.2.5 on 2023-12-27 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_stock_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 27, 5, 25, 13, 434996, tzinfo=datetime.timezone.utc)),
        ),
    ]
