# Generated by Django 4.2.5 on 2023-12-27 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_stock_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 27, 7, 34, 31, 595697, tzinfo=datetime.timezone.utc)),
        ),
    ]
