# Generated by Django 4.2.5 on 2023-12-28 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_alter_stock_current_date_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='transaction_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Pending', 'Pending')], default=datetime.datetime(2023, 12, 28, 10, 32, 33, 463531, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 28, 10, 32, 23, 605765, tzinfo=datetime.timezone.utc)),
        ),
    ]
