# Generated by Django 4.2.5 on 2023-12-28 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_salary_transaction_type_alter_stock_current_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='salary',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 28, 10, 41, 36, 443956, tzinfo=datetime.timezone.utc)),
        ),
    ]
