# Generated by Django 4.2.5 on 2023-12-28 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_rename_salary_salary_amount_alter_stock_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 12, 28, 10, 42, 48, 633252, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 12, 28, 10, 42, 41, 295711, tzinfo=datetime.timezone.utc)),
        ),
    ]
