# Generated by Django 4.2.5 on 2023-12-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billrecord',
            name='bill_number',
            field=models.CharField(max_length=100),
        ),
    ]
