# Generated by Django 4.2.5 on 2023-12-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_billrecord_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billrecord',
            name='bill_number',
        ),
    ]
