# Generated by Django 4.2.5 on 2023-12-24 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_billrecord_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='YogaMember/%Y/%m/%d')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('membership_types', models.CharField(choices=[('basic', 'Basic'), ('gold', 'Gold')], default='basic', max_length=20)),
                ('billing_address', models.CharField(choices=[('online', 'Online'), ('case', 'Case')], max_length=20)),
                ('date_of_signature', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact2', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
