# Generated by Django 4.2.5 on 2023-12-24 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_yogamember'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogamember',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=datetime.datetime(2023, 12, 24, 7, 16, 53, 82597, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
