# Generated by Django 4.2.5 on 2023-12-26 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_member_alter_yogamember_street_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yogamember',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
