# Generated by Django 4.2.5 on 2023-12-27 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrecord',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 5, 25, 21, 540242, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
