# Generated by Django 4.2.5 on 2023-12-27 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=datetime.datetime(2023, 12, 27, 7, 34, 38, 680593, tzinfo=datetime.timezone.utc), upload_to='product/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
