# Generated by Django 4.2.5 on 2023-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_cashtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Pending', 'Pending')], max_length=8),
        ),
    ]
