# Generated by Django 4.2.5 on 2023-12-28 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_sport_vocalrecording_sportplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocalrecording',
            name='recording_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 8, 9, 19, 189870, tzinfo=datetime.timezone.utc)),
        ),
    ]
